name: Matrix Demo
on: push
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      