name: Matrix Demo
on: push
# jobs:
#   build:
#     strategy:
#       matrix:
#         version: [10, 12, 14],
#         operating-system: [ubuntu-latest, windows-latest]
#     runs-on: ubuntu-latest # ${{ matrix.operating-system }}
#     steps:
#       - name: Get Code
#         uses: actions/checkout@v3
#       - name: Install Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 14 #${{ matrix.node-version }}
#       - name: Install Dependencies
#         run: npm ci
#       - name: Build Project
#         run: npm run build
      


jobs:
  example_matrix:
    strategy:
    matrix:
      version: [10, 12, 14]
  runs-on: ubuntu-latest
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}